name: CSE Trade Summary Daily Download

on:
  schedule:
    # Runs every day at 4:00 PM Sri Lankan Time (10:30 AM UTC)
    # Sri Lanka is UTC+5:30, so 4:00 PM LKT = 10:30 AM UTC
    - cron: '30 10 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write  # Allow writing to repository content
  actions: read    # Allow reading action metadata

jobs:
  download-trade-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome browser
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Create downloads directory
      run: mkdir -p downloads
      
    - name: Configure git
      run: |
        git config --global user.name "CSE Bot"
        git config --global user.email "cse-bot@users.noreply.github.com"
        
    - name: Run CSE automation
      run: python cse_automation.py
      
    - name: Check downloaded files
      run: |
        echo "Files in downloads directory:"
        ls -la downloads/ || echo "Downloads directory is empty"
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
      run: |
        git add downloads/
        if git diff --staged --quiet; then
          echo "No new files to commit"
        else
          # Fetch latest changes
          git fetch origin main
          
          # Commit our changes
          git commit -m "Add CSE trade summary data - $(date '+%Y-%m-%d %H:%M:%S UTC')"
          
          # Rebase on top of latest changes and push
          git pull --rebase origin main
          git push origin main
        fi
