name: CSE Trade Data Download

on:
  schedule:
    # Runs daily at 4:00 PM Sri Lankan Time (10:30 AM UTC)
    # Sri Lanka is UTC+5:30, so 4:00 PM LKT = 10:30 AM UTC
    - cron: '30 10 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  download-trade-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      
    - name: Clean WebDriver Manager cache
      run: |
        echo "Cleaning WebDriver Manager cache..."
        rm -rf ~/.wdm
        rm -rf /home/runner/.wdm
        rm -rf /tmp/.wdm
        rm -rf $HOME/.wdm
        find /home/runner -name "*chromedriver*" -type f 2>/dev/null || true
        echo "Cache cleanup complete"
        
    - name: Setup virtual display
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify Chrome and ChromeDriver
      run: |
        google-chrome --version
        chromedriver --version
        which chromedriver
        ls -la $(which chromedriver)
        echo "DISPLAY=$DISPLAY"
        echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
        
    - name: Create downloads directory
      run: mkdir -p downloads
      
    - name: Run CSE downloader
      run: |
        export DISPLAY=:99
        export GITHUB_ACTIONS=true
        export CI=true
        # Prevent WebDriver Manager from being used
        export WDM_LOCAL=0
        # Make sure we're using the system chromedriver
        which chromedriver
        chromedriver --version
        python cse_downloader.py
      env:
        DISPLAY: :99
        GITHUB_ACTIONS: true
        CI: true
        WDM_LOCAL: 0
        
    - name: List downloaded files
      run: ls -la downloads/
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add downloads/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Auto-download CSE trade data - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
